version: "3.8"
services:
  booking_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
